05:47:33 PM: DEBUG [logger_base.py:19] Mensaje a nivel debug
05:47:33 PM: INFO [logger_base.py:20] Mensaje a nivel de info
05:47:33 PM: WARNING [logger_base.py:21] Mensaje a nivel de warning
05:47:33 PM: ERROR [logger_base.py:22] Mensaje a nivel de error
05:47:33 PM: CRITICAL [logger_base.py:23] Mensaje a nivel critical
05:59:19 PM: DEBUG [persona.py:52] 
            Id Persona: 1, Nombre: Juan
            Apellido: Barreto, Email: jb@email.com 
        
06:01:40 PM: DEBUG [persona.py:52] 
            Id Persona: 1, Nombre: Juan
            Apellido: Barreto, Email: jb@email.com 
        
06:04:50 PM: DEBUG [persona.py:52] 
            Id Persona: 1, Nombre: Juan
            Apellido: Barreto, Email: jb@email.com 
        
06:04:50 PM: DEBUG [persona.py:56] 
            Id Persona: None, Nombre: Juan
            Apellido: Perez, Email: jperez@email.com 
        
06:06:26 PM: DEBUG [persona.py:52] 
            Id Persona: 1, Nombre: Juan
            Apellido: Barreto, Email: jb@email.com 
        
06:06:26 PM: DEBUG [persona.py:56] 
            Id Persona: None, Nombre: Juan
            Apellido: Perez, Email: jperez@email.com 
        
06:06:26 PM: DEBUG [persona.py:60] 
            Id Persona: 1, Nombre: None
            Apellido: None, Email: None 
        
07:48:09 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x74431254fec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
07:50:29 PM: ERROR [conexion.py:23] Conexion exitosa: <connection object at 0x726fa4e1bec0; dsn: 'user=admin password=xxx dbname=test_db host=localhost port=5432', closed: 0>
07:50:29 PM: DEBUG [conexion.py:36] Se abrio correctamente el cursor: <cursor object at 0x726fa4cc25c0; closed: 0>
